# Generated by Django 2.2.1 on 2019-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='cloth_id',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='cloth',
            name='cloth_type',
            field=models.CharField(choices=[('SH', '鞋子'), ('OT', '其它'), ('UG', '上衣'), ('PT', '裤子'), ('CT', '帽子')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='cloth',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
