# Generated by Django 2.2.1 on 2019-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_auto_20190903_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='cloth_type',
            field=models.CharField(choices=[('PT', '裤子'), ('SH', '鞋子'), ('OT', '其它'), ('UG', '上衣'), ('CT', '帽子')], default='null', max_length=5),
        ),
    ]
