# Generated by Django 2.1.7 on 2019-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='color',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='size',
            field=models.CharField(default='XL', max_length=30),
            preserve_default=False,
        ),
    ]
