# Generated by Django 2.2.1 on 2019-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190305_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
