# Generated by Django 2.1.7 on 2019-02-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloth', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhongChou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number', models.IntegerField()),
                ('paid_number', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ZhongChouDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('zhongchou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongchou.ZhongChou')),
            ],
        ),
        migrations.AddField(
            model_name='zhongchou',
            name='user',
            field=models.ManyToManyField(through='zhongchou.ZhongChouDetail', to='user.User'),
        ),
    ]
