# Generated by Django 2.1.7 on 2019-02-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhongchou', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhongchou',
            old_name='paid',
            new_name='all_paid',
        ),
    ]
