# Generated by Django 2.2.1 on 2019-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='email',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designer',
            name='password',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='telephone',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AlterField(
            model_name='designer',
            name='intro',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
