# Generated by Django 2.2.1 on 2019-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('send_type', models.CharField(choices=[('RE', '用户注册'), ('FG', '修改密码')], max_length=10)),
            ],
        ),
    ]
