# Generated by Django 2.1.7 on 2019-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_portrait',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
